[tools]
# Languages and Runtimes
node = "lts"
bun = "1.3"
deno = "latest"
go = "1.24"
python = "3.13"
java = "corretto-21.0.8"
gradle = "8.5"

# Package managers
pipx = "latest"
uv = "latest"

# Code Assistants
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:aicommit2" = "latest"

# LSPs and formatters
"aqua:LuaLS/lua-language-server" = "latest"
"cargo:https://github.com/oxalica/nil" = { version = "branch:main", crate = "nil" }
"go:github.com/a-h/templ/cmd/templ" = "latest"
"go:github.com/google/yamlfmt/cmd/yamlfmt" = "latest"
"go:github.com/lasorda/protobuf-language-server" = "master"
"go:golang.org/x/tools/gopls" = "latest"
"go:mvdan.cc/gofumpt" = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:@microsoft/compose-language-service" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:pyright" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
"pipx:autotools-language-server" = "latest"
# rust-analyzer = `rustup component add rust-analyzer`
protobuf = "latest"
ruff = "latest"
shfmt = "latest"
stylua = "latest"
terraform-ls = "latest"

# Kubernetes
kubectl = "latest"
helm = "latest"
helm-diff = "latest"
krew = "latest"
istioctl = "latest"
k9s = "latest"

# IaC Tools
terraform = "1.9.3"
terragrunt = "latest"
ansible = "latest"

# CLI
awscli = "latest"
bat = "latest"
carapace = "latest"
direnv = "latest"
duckdb = "latest"
dust = "latest"
fd = "latest"
fx = "latest"
fzf = "latest"
git-cliff = "latest"
gomigrate = "latest"
hugo = "v0.145.0"
jq = "latest"
just = "latest"
lsd = "latest"
neovim = "latest"
rclone = "latest"
restic = "latest"
ripgrep = "latest"
starship = "latest"
television = "latest"
tmux = "latest"
watchexec = "latest"
yq = "latest"
zoxide = "latest"
"cargo:nu" = "latest" # nushell
"cargo:xh" = "latest"
"go:github.com/natesales/q" = "latest"

# Git Tools
gh = "latest"
lazygit = "latest"
pre-commit = "latest"

# Encryption
sops = "latest"
age = "latest"
fnox = "latest"

# Media
ffmpeg = "latest"
# "pipx:yt-dlp" = "latest"
# "pipx:gallery-dl" = "latest"

[settings]
experimental = true

[settings.npm]
bun = true
