[tools]
# Languages and Runtimes
node = "24.11.1"
bun = "1.3"
go = "1.24"
python = "3.13"
rust = { version = "stable", components = "rust-analyzer", targets = "wasm32-wasip1" }

# Package managers
pipx = "latest"
uv = "latest"

# Coding Assistants
claude = "latest"
codex = "latest"
"npm:opencode-ai" = "latest"
"npm:@openchamber/web" = "latest"
"npm:openclaw" = "latest"
"npm:@fission-ai/openspec" = "latest"
"npm:aicommit2" = "latest"

# LSPs and formatters
"aqua:LuaLS/lua-language-server" = "latest"
"cargo:https://github.com/oxalica/nil" = { version = "branch:main", crate = "nil" }
"cargo:kdlfmt" = { version = "latest" }
"go:github.com/a-h/templ/cmd/templ" = "latest"
"go:github.com/google/yamlfmt/cmd/yamlfmt" = "latest"
"go:github.com/lasorda/protobuf-language-server" = "master"
"go:golang.org/x/tools/gopls" = "latest"
"go:mvdan.cc/gofumpt" = "latest"
"npm:@astrojs/language-server" = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:@microsoft/compose-language-service" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:@taplo/cli" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:jsonlint" = "latest"
"npm:pyright" = "latest"
"npm:svelte-language-server" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
"pipx:autotools-language-server" = "latest"
"pipx:ty" = "latest"
"pipx:yamllint" = "latest"
# rust-analyzer = `rustup component add rust-analyzer`
golangci-lint = "latest"
protobuf = "latest"
ruff = "latest"
shfmt = "latest"
stylua = "latest"
terraform-ls = "latest"

# Kubernetes
kubectl = "latest"
helm = "latest"
helm-diff = "latest"
krew = "latest"
istioctl = "latest"
cmctl = "latest"
stern = "latest"
k9s = "latest"
kind = "latest"

# IaC Tools
terraform = "1.9.3"
terragrunt = "latest"
# pulumi = "latest"
# ansible = "latest"

# CLI
awscli = { version = "latest", symlink_bins = "true" }
bat = "latest"
carapace = "latest"
direnv = "latest"
duckdb = "latest"
dust = "latest"
fd = "latest"
fx = "latest"
fzf = "latest"
git-cliff = "latest"
grpcurl = "latest"
helix = "latest"
hugo = "v0.145.0"
jq = "latest"
just = "latest"
lsd = "latest"
neovim = "latest"
prek = "latest"
rclone = "latest"
restic = "latest"
ripgrep = "latest"
starship = "latest"
tmux = "latest"
wasmtime = "latest"
watchexec = "latest"
yazi = "latest"
yq = "latest"
zellij = "latest"
zoxide = "latest"

"cargo:xh" = "latest"
"go:github.com/golang-migrate/migrate/v4/cmd/migrate" = { version = "latest", tags = "sqlite,postgres" }
"go:github.com/jpillora/chisel" = "latest"
"go:github.com/natesales/q" = "latest"
"go:github.com/pranshuparmar/witr/cmd/witr" = "latest"
"npm:@beaconbay/ck-search" = "latest"
"npm:httpyac" = "latest"
"pipx:mcp-obsidian" = "0.2.1"

# Git Tools
gh = "latest"
lazygit = "latest"
pre-commit = "latest"

# Encryption
sops = "latest"
age = "latest"
fnox = "latest"

# Disabled Tools
# deno = "latest"
# java = "corretto-21.0.8"
# gradle = "8.5"
# argo = "latest"
# television = "latest"
# "cargo:nu" = "latest" # nushell
# "pipx:yt-dlp" = "latest"
# "pipx:gallery-dl" = "latest"

[settings]
experimental = true

[settings.npm]
bun = true
[settings.pipx]
uvx = true
