default_provider = "age"

[providers.age]
type = "age"
recipients = ["age1fgs45gewp9z6uz20mkvmy4xypvwen9wnjhhhgjcsl0cy0pq3qqgs4vdpd7"]

[secrets]
HELLO= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZE9WVGNSanFmYmdIZnZuOVJ2bU1ReTQxYVNKM2xyWkYzcVVYT1lzZ0dJCkszSmUyYWh4aUo1ZURxNlZaTVBBdVByQ3dCZGJ6MmJnVUxmR3FTR043TTQKLT4gdFgqLWdyZWFzZSAhWGRrXCxPIEMyUDUgVCpmN0VACmZwRDVSYmVDRVFoWTV0ZlF3KzFFQ3QzQmZsSWxwU0djQ2NiOG1XU2VtY1A3NVZNK2c4elM0VGYzUXI5R3dvRVgKWW5vZFNkOAotLS0gSVRCdllnV0RUWityUUFMSG9WVHE1RXZOWk5ISlN0S0MwdHJtcmhZMGNlawoI0Kt/rEygRN72gVa3QElGA44muwVQmLgaZWWb7orVyEBRVUtZdA==" }
